# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
server: true
server_port: 4000
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://kredinor.github.com
title : kredinor @ github

author :
  name : Kredinor
  email : github@kredinor.no
  github : kredinor
  twitter : KredinorDevs
